displayName=Warriors Guild Catapult Helper
author=Thaspian
description=Highlights the correct defensive option for the warrior's guild catapult projectiles
tags=catapult, warrior, warriors, guild, minigame
version=
plugins=com.warriorsguildcatapult.WarriorsGuildCatapult
build=standard