displayName=Warriors Guild Catapult Helper
author=Thaspian
description=Highlights the correct defensive option for the warrior's guild catapult projectiles
tags=catapult, warrior, warriors, guild
version=1.0
plugins=com.warriorsguildcatapult.WarriorsGuildCatapult
build=standard